<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PedidoSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('pedido')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        DB::table('pedido')->insert([
            [
                'id_pedido' => 1,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 2,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 3,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-03 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 4,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-04 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 5,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 6,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 7,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-07 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 8,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-08 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 9,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-09 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 10,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-10 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 11,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-11 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 12,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-12 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 13,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-13 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 14,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-14 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 15,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-15 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 16,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-16 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 17,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-17 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 18,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-18 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 19,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 20,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-20 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 21,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-21 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 22,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-22 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 23,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-23 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 24,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-24 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 25,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-25 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 26,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-26 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 27,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-27 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 28,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-28 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 29,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-29 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 30,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-30 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 100,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-01 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 101,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-02 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 102,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-03 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 103,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-04 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 104,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-05 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 105,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-06 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 106,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-07 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 107,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-08 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 108,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-09 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 109,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-10 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 110,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-11 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 111,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-12 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 112,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-13 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 113,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-14 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 114,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-15 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 115,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-16 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 116,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-17 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 117,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-18 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 118,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-19 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 119,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-20 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 120,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-21 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 121,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-22 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 122,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-23 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 123,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-24 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 124,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-25 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 125,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-26 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 126,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-27 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 127,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-28 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 128,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-29 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 129,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-30 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 130,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-31 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 1,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 2,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 3,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-03 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 4,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-04 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 5,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 6,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 7,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-07 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 8,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-08 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 9,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-09 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 10,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-10 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 11,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-11 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 12,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-12 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 13,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-13 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 14,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-14 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 15,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-15 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 16,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-16 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 17,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-17 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 18,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-18 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 19,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 20,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-20 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 21,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-21 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 22,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-22 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 23,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-23 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 24,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-24 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 25,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-25 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 26,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-26 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 27,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-27 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 28,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-28 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 29,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-29 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 30,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-30 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 1,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 2,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 3,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-03 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 4,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-04 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 5,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 6,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 7,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-07 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 8,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-08 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 9,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-09 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 10,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-10 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 11,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-11 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 12,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-12 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 13,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-13 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 14,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-14 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 15,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-15 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 16,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-16 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 17,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-17 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 18,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-18 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 19,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 20,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-20 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 21,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-21 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 22,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-22 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 1,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 2,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 3,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-03 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 4,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-04 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 5,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 6,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 7,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-07 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 8,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-08 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 9,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-09 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 10,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-10 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 11,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-11 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 12,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-12 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 13,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-13 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 14,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-14 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 15,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-15 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 16,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-16 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 17,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-17 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 18,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-18 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 19,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 20,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-20 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 21,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-21 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 22,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-22 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 23,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-23 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 24,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-24 08:00:00',
                'estado_actual' => 2,
                'eliminado' => 0,
            ],
        ]);
    }
}
