<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PedidoSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('pedido')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('pedido')->insert([
            [
                'id_pedido' => 1,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-01 08:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 2,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-01 09:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 3,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-01 11:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 4,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-01 14:20:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 5,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-01 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 6,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-01 19:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 7,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-02 07:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 8,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-02 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 9,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-02 12:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 10,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-02 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 11,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-02 18:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 12,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-02 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 13,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-03 08:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 14,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-03 10:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 15,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-03 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 16,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-03 16:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 17,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-03 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 18,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-04 09:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 19,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-04 11:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 20,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-04 14:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 21,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-04 17:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 22,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-04 20:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 23,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-05 08:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 24,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-05 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 25,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-05 13:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 26,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-05 16:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 27,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-05 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 28,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-05 21:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 29,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-08 08:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 30,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-08 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 31,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-08 15:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 32,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-08 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 33,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-08 21:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 34,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-09 09:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 35,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-09 13:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 36,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-09 17:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 37,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-09 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 38,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-10 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 39,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-10 14:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 40,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-10 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 41,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-15 11:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 42,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-15 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 43,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-15 20:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 44,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-16 09:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 45,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-16 14:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 46,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-16 18:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 47,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-22 12:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 48,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-22 17:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 49,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-22 21:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 50,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-02-23 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 51,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-02-23 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 52,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-02-23 19:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 53,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-01 08:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 54,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-01 11:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 55,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-01 14:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 56,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-01 17:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 57,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-01 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 58,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-02 09:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 59,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-02 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 60,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-02 16:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 61,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-02 19:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 62,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-03 10:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 63,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-03 14:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 64,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-03 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 65,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-03 21:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 66,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-04 08:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 67,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-04 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 68,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-04 16:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 69,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-04 19:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 70,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-05 11:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 71,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-05 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 72,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-05 18:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 73,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-05 21:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 74,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-08 09:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 75,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-08 13:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 76,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-08 17:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 77,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-08 20:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 78,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-09 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 79,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-09 14:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 80,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-09 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 81,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-09 21:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 82,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-15 12:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 83,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-15 16:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 84,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-15 19:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 85,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-16 11:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 86,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-16 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 87,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-16 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 88,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-22 13:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 89,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-22 17:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 90,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-22 20:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 91,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-23 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 92,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-23 14:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 93,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-23 18:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 94,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-29 12:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 95,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-03-29 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 96,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-03-29 19:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 97,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-03-30 11:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 98,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 08:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 99,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-01 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 100,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-01 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 101,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-01 16:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 102,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-01 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 103,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-01 21:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 104,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 09:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 105,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-02 12:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 106,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-02 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 107,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-02 18:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 108,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-02 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 109,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-03 11:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 110,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-03 14:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 111,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-03 17:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 112,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-03 20:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 113,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 10:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 114,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-05 13:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 115,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-05 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 116,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-05 19:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 117,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-05 21:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 118,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-06 09:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 119,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 120,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-06 15:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 121,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-06 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 122,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-06 20:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 123,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-12 11:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 124,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-12 14:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 125,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-12 17:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 126,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-12 19:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 127,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-13 10:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 128,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-13 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 129,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-13 16:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 130,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-13 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 131,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 12:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 132,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-19 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 133,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-19 18:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 134,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-19 21:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 135,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-20 09:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 136,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-20 12:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 137,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-20 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 138,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-20 18:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 139,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-26 11:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 140,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-04-26 14:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 141,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-04-26 17:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 142,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-04-27 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 143,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-01 09:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 144,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-01 11:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 145,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-01 14:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 146,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-01 17:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 147,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-01 20:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 148,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-02 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 149,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-02 13:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 150,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-02 16:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 151,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-02 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 152,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-03 11:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 153,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-03 14:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 154,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-03 16:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 155,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-03 19:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 156,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-04 09:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 157,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-04 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 158,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-04 15:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 159,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-04 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 160,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-04 20:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 161,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-10 10:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 162,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-10 12:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 163,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-10 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 164,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-10 18:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 165,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-10 21:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 166,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-11 11:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 167,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-11 14:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 168,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-11 17:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 169,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-11 19:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 170,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-17 12:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 171,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-17 14:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 172,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-17 17:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 173,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-17 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 174,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-18 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 175,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-18 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 176,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-18 16:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 177,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-18 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 178,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-24 11:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 179,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-24 13:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 180,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-24 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 181,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-24 19:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 182,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-25 10:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 183,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-25 13:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 184,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-25 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 185,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-05-31 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 186,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-05-31 15:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 187,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-05-31 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 188,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-01 08:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 189,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-01 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 190,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-01 13:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 191,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-01 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 192,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-01 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 193,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-01 20:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 194,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-02 08:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 195,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-02 11:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 196,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-02 14:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 197,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-02 16:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 198,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-02 19:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 199,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-03 09:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 200,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-03 12:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 201,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-03 15:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 202,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-03 17:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 203,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-03 20:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 204,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-04 08:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 205,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-04 11:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 206,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-04 13:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 207,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-04 16:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 208,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-04 18:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 209,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-05 09:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 210,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-05 12:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 211,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-05 14:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 212,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-05 17:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 213,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-05 19:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 214,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-06 08:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 215,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-06 10:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 216,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-06 13:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 217,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-06 15:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 218,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-06 18:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 219,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-07 09:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 220,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-07 11:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 221,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-07 14:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 222,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-07 16:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 223,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-07 19:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 224,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-08 08:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 225,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-08 11:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 226,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-08 13:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 227,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-08 16:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 228,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-08 18:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 229,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-09 09:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 230,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-09 12:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 231,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-09 15:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 232,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-09 17:45:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 233,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-09 20:15:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 234,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-10 08:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 235,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-10 10:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 236,
                'id_usuario_mesero' => 1,
                'fecha_hora_registro' => '2025-06-10 13:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 237,
                'id_usuario_mesero' => 2,
                'fecha_hora_registro' => '2025-06-10 15:30:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
            [
                'id_pedido' => 238,
                'id_usuario_mesero' => 3,
                'fecha_hora_registro' => '2025-06-10 18:00:00',
                'estado_actual' => 6,
                'eliminado' => 0,
            ],
        ]);
    }
}
