<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('producto')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('producto')->insert([
            [
                'id_producto' => 1,
                'nombre' => 'Café Americano',
                'descripcion' => 'Café negro caliente',
                'id_categoria' => 1,
                'precio' => 8.50,
                'disponibilidad' => 0,
                'cantidad_disponible' => 2,
                'imagen' => 'https://us.123rf.com/450wm/farknot/farknot1801/farknot180100055/94523530-imagen-del-primer-de-la-taza-de-café-caliente-de-americano-en-la-tabla-de-madera-del-vintage-en.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 2,
                'nombre' => 'Latte',
                'descripcion' => 'Café con leche vaporizada',
                'id_categoria' => 1,
                'precio' => 10.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 994,
                'imagen' => 'https://izlah.mx/cdn/shop/products/Bxtr_Vintage_2.png?v=1589587917',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 3,
                'nombre' => 'Té verde',
                'descripcion' => 'Infusión de té verde',
                'id_categoria' => 1,
                'precio' => 9.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 1,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVli4Sh8y9-OskZmWtaiKjOhS4ocpuApZvFg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 4,
                'nombre' => 'Jugo de naranja',
                'descripcion' => 'Jugo natural exprimido',
                'id_categoria' => 2,
                'precio' => 9.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://us.123rf.com/450wm/nadezhda1906/nadezhda19061705/nadezhda1906170500137/77961693-escena-de-la-mañana-de-jugos-de-naranja-fresca-servido-en-el-bar.jpg?ver=6',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 5,
                'nombre' => 'Cheesecake',
                'descripcion' => 'Torta de queso crema',
                'id_categoria' => 3,
                'precio' => 12.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://images.ctfassets.net/trvmqu12jq2l/VkBle3ndRRRtHWrOhaKKj/01190beab12083d50f421e7efdc3b404/CxBlog-DD-CheesecakeFactory-SaltedCaramel.jpg?q=70&w=480',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 10,
                'nombre' => 'Pastel de frutillas',
                'descripcion' => 'pastel con frutillas y queso',
                'id_categoria' => 3,
                'precio' => 18.00,
                'disponibilidad' => 0,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU6MQw_fCwfVFSeAQAysA-KceDKAVWYQXSmw&s',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 11,
                'nombre' => 'Macchiato',
                'descripcion' => 'Espresso manchado con una gota de leche texturizada.',
                'id_categoria' => 1,
                'precio' => 15.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://www.acouplecooks.com/wp-content/uploads/2020/10/how-to-make-a-macchiato-003s.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 12,
                'nombre' => 'Espresso Americano',
                'descripcion' => 'Doble shot de espresso diluido en agua.',
                'id_categoria' => 1,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://gourmetdemexico.com.mx/wp-content/uploads/2016/08/field_image_head-espresso.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 13,
                'nombre' => 'Cortado',
                'descripcion' => 'Leche texturizada con la temperatura ideal para cortar el espresso.',
                'id_categoria' => 1,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsD2RKaN-OY-35n37KdqGfpg4CgCgIGvH8VA&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 14,
                'nombre' => 'Flat White',
                'descripcion' => 'Doble ristretto con leche texturizada.',
                'id_categoria' => 1,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/flat-white-d8ada0f.jpg?quality=90&resize=440,400',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 15,
                'nombre' => 'Submarino',
                'descripcion' => 'Leche texturizada con una barra de chocolate amargo entero.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiDoyB26ej8-yH7LmF2I7uOMm81SgT1R5sqg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 16,
                'nombre' => 'Té Latte',
                'descripcion' => 'Té con leche.',
                'id_categoria' => 1,
                'precio' => 22.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://i.blogs.es/e97540/te-chai-latte/1366_2000.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 17,
                'nombre' => 'Chocolate caliente',
                'descripcion' => 'Cocoa con leche, acompañada de dos marshmallows.',
                'id_categoria' => 1,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE4-CtCbPsEWMl3jGuPwXkSaNc0TadMMYiTw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 18,
                'nombre' => 'Té Chai',
                'descripcion' => 'Té negro, especias y leche texturizada.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://www.splenda.com/wp-content/themes/bistrotheme/assets/recipe-images/chai-tea-blend.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 19,
                'nombre' => 'Matcha Latte',
                'descripcion' => 'Té verde matcha con leche texturizada.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 4,
                'imagen' => 'https://munchingwithmariyah.com/wp-content/uploads/2020/06/IMG_0748.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 20,
                'nombre' => 'Niebla en Londres',
                'descripcion' => 'Té negro, especias y leche texturizada.',
                'id_categoria' => 1,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRLd71Ip3S8DnXAInWaFxw1TGtvNgJDLLhJIZq29PuijnO9z15YE2B0FKJgRjlw5boO_A&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 21,
                'nombre' => 'Coldbrew',
                'descripcion' => 'Café frío de origen: extraído durante 16 horas.',
                'id_categoria' => 2,
                'precio' => 22.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpiFaDmfujrauZMwSXoWbTJTSbbFd94xlfQw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 22,
                'nombre' => 'Café con hielo',
                'descripcion' => 'Café de origen destilado con hielos.',
                'id_categoria' => 2,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5tS0no6EB1MOMI9ug6Bn9BC0_sJry71iLdQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 23,
                'nombre' => 'Latte frío',
                'descripcion' => 'Doble shot de espresso, leche texturizada y hielo.',
                'id_categoria' => 2,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN_f3AtqsjG9nkkbUvnug0mSZOtKkgmH9Rog&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 24,
                'nombre' => 'Café con leche frappeado',
                'descripcion' => 'Todo ya está dicho.',
                'id_categoria' => 2,
                'precio' => 28.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFYEuJgeYsnql0MFK6btdouwtM2AZP7DZqgXPgYWwmjarpeyXkK2wWhW6w2spGkDzvxEY&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 25,
                'nombre' => 'Affogato',
                'descripcion' => 'Dos porciones de helado de vainilla con doble shot de espresso.',
                'id_categoria' => 2,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://static01.nyt.com/images/2021/08/15/magazine/affogato/affogato-mediumSquareAt3X-v2.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 26,
                'nombre' => 'Shakerato',
                'descripcion' => 'Bebida refrescante a base de espresso, naranja y albahaca.',
                'id_categoria' => 2,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQno3nzqXK0a36Wcqfq2oCXW-LXJNHA5Qrnpw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 27,
                'nombre' => 'Espresso Tonic',
                'descripcion' => 'Dos shots de espresso y agua tónica.',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://res.cloudinary.com/htt8g4cd/images/f_auto,q_auto/v1730823639/wp/07_23_Espresso_Tonic_HERO_Stocksy_4062559_1920x1280/07_23_Espresso_Tonic_HERO_Stocksy_4062559_1920x1280.jpg?_i=AA',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 28,
                'nombre' => 'Jugos naturales',
                'descripcion' => 'Jugos naturales (con leche).',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSjMBTsZ_ExFsCLjygT2G0OYpFPm1JMXm2lg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 29,
                'nombre' => 'Mix de frutas',
                'descripcion' => 'Mix de frutas.',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBekkfntZCXh7BkAfNSAxshjrqbNDosbqjMQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 30,
                'nombre' => 'Limonada',
                'descripcion' => 'Limonada (puedes pedirla con hierba buena).',
                'id_categoria' => 2,
                'precio' => 0.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.conasi.eu/blog/wp-content/uploads/2019/09/limonada-de-albahaca-1.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 31,
                'nombre' => 'Strawberry Matcha Latte',
                'descripcion' => 'Matcha con fresa y leche.',
                'id_categoria' => 2,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0CLS6WcPUlhX7Wc75js56dkgeDGyCCdk1lQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 32,
                'nombre' => 'Ice Tea',
                'descripcion' => 'Té frío de infusiones clásicas o especiales.',
                'id_categoria' => 2,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0JqdakweKyrQByMMYMA6Cy9XiXu8MMOBBsw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 33,
                'nombre' => 'Cheesecake de limón',
                'descripcion' => 'Cheesecake con base de galleta y salsa de limón.',
                'id_categoria' => 3,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFmE0hxPLjx5bEUhsNvOTcKxbD1XijhZseug&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 34,
                'nombre' => 'Cheesecake de maracuyá',
                'descripcion' => 'Cheesecake con base de galleta de chocolate y salsa de maracuyá.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThtxktek3xo_UccVBO57IHLnYsIDiQJ6fJ8TVXpNpsbtPgiCJgeOUqAHlGQK9ZR06IEX4&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 35,
                'nombre' => 'Torta de zanahoria',
                'descripcion' => 'Torta de zanahoria con cobertura de queso crema.',
                'id_categoria' => 3,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0JYLWJBlRtgO8Az2pDV9ffpBxuWeghz1xMQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 36,
                'nombre' => 'Crepes de dulce de leche con fruta',
                'descripcion' => 'Rellenos de dulce de leche acompañados con frutas de temporada.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://d1uz88p17r663j.cloudfront.net/original/a83618e0a68ec34aa3e28ad3171f8705_Dulce_de_Leche_Crepes_with_Banana.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 37,
                'nombre' => 'Brownie',
                'descripcion' => 'Hecho en casa, en su punto.',
                'id_categoria' => 3,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://i.blogs.es/22b5c5/brownie/840_560.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 38,
                'nombre' => 'Apple Crumble',
                'descripcion' => 'Tarta de manzana con yogur de vainilla.',
                'id_categoria' => 3,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://hips.hearstapps.com/hmg-prod/images/apple-crumble-recipe-2-66c641fec6b40.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=1200:*',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 39,
                'nombre' => 'Tostadas francesas al cubo',
                'descripcion' => 'Pan de molde con relleno de pancakes.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy1TkSx2soZIyCOiwlf_U4xsuPUhB01EjyEQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 40,
                'nombre' => 'Frappé fruta de temporada',
                'descripcion' => 'Frappé de fruta de temporada.',
                'id_categoria' => 3,
                'precio' => 24.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://servinox.com.mx/blog/wp-content/uploads/2015/05/smoothie-and-coffee-244x300.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 41,
                'nombre' => 'Frappé pie de limón',
                'descripcion' => 'Frappé con sabor a pie de limón.',
                'id_categoria' => 3,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSbskqbvpF33oWSFOHp28jkgGZ_2_Az3LV3w&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 42,
                'nombre' => 'Frappé orejón',
                'descripcion' => 'Frappé orejón.',
                'id_categoria' => 3,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgUJUaar8wXmdm6uwOiJwqLkr9hamaVrBQOw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 43,
                'nombre' => 'Desayuno Typica',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 49.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcMCFsVazxz-KY-Z9DjycqzaTx2VNflk-d3w&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 44,
                'nombre' => 'Desayuno Americano',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 46.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRY2U8ANg31mvvw4345_maWqeWgrMBiMkCfQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 45,
                'nombre' => 'Desayuno Saludable',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 34.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQN5FjmfC6-V_q9ProMil7LTUtVncaiBbuNg&',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 46,
                'nombre' => 'Duo de Croissants',
                'descripcion' => 'Se elige uno dulce y uno salado.',
                'id_categoria' => 4,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuj1nH0t96XWJ_Zs-S1IEW1FG0GysQUfTcDA&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 47,
                'nombre' => 'Panqueques',
                'descripcion' => 'Dos panqueques esponjosos de mantequilla.',
                'id_categoria' => 4,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShsTFR136GmyqoEJIaTuYvPJtf2vJAmcv4AA&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 48,
                'nombre' => 'Croissant de chocolate',
                'descripcion' => 'Croissant de masa hojaldrada, relleno con chocolate.',
                'id_categoria' => 4,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://comedera.com/wp-content/uploads/sites/9/2022/02/croissant-relleno-de-chocolate.jpg?w=4096',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 49,
                'nombre' => 'Ensalada de frutas',
                'descripcion' => 'Variedad de frutas de estación con jugo de naranja.',
                'id_categoria' => 4,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIIwMBo0ttWTw2CSYteKz9WsLlJXTRDYRyLw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 50,
                'nombre' => 'Bowl Açaí',
                'descripcion' => 'Deliciosa mezcla de açaí y frutas de estación.',
                'id_categoria' => 4,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV7mufGZULOKQzdLDu0XupPxiR4HKusmEULQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 51,
                'nombre' => 'Desayuno Waso',
                'descripcion' => 'Carne salteada a lo Waso y verduras con arroz.',
                'id_categoria' => 4,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://d36fw6y2wq3bat.cloudfront.net/recipes/salteado-de-arroz-verduras-y-ternera/900/salteado-de-arroz-verduras-y-ternera_version_1652877970.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 52,
                'nombre' => 'Desayuno Compartido',
                'descripcion' => 'Para compartir, incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 95.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNCvgJi1x_tY6wLCJ-ZeN7QQOXcPQCsvD3XQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 53,
                'nombre' => 'Chorizo',
                'descripcion' => 'Dos chorizos al vino blanco con papas y chucrut.',
                'id_categoria' => 4,
                'precio' => 38.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXhmu2Rm7AV1hWFCDTrD_p54Otr73h7c5QHw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 54,
                'nombre' => 'Cuñapés fritos',
                'descripcion' => 'Cuñapés fritos acompañados con salsa de sésamo.',
                'id_categoria' => 4,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg6Fm34MUp8eXQt7bvKiWL5UVU2U3C1xapfg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 55,
                'nombre' => 'Anticucho',
                'descripcion' => 'Corazón de res con papas y ají.',
                'id_categoria' => 4,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMJSpbzj9rEbLzZXV6lxYpz4wFYJxIMUy8gQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 56,
                'nombre' => 'Combo rellenos',
                'descripcion' => 'Plátano dulce con carne deshilachada y queso.',
                'id_categoria' => 4,
                'precio' => 41.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLScw7YyR4a5JZnkD3ko4HeqV8DyaGrpQm9g&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 57,
                'nombre' => 'Charque',
                'descripcion' => 'Charque con salsa de tres quesos en pan marraqueta.',
                'id_categoria' => 4,
                'precio' => 38.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-b_kViJ4JWVG9jbnE2JwVk5iuwmcjJXhXvw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 58,
                'nombre' => 'Sándwich palta',
                'descripcion' => 'Sándwich de palta con cebolín y tomate confitado.',
                'id_categoria' => 4,
                'precio' => 27.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRigIPg5uKzAvxekEAFMd3jPVfzmC-yWGM0Lg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 59,
                'nombre' => 'Sándwich Pollo',
                'descripcion' => 'Sándwich de pollo con cebolla dulce.',
                'id_categoria' => 4,
                'precio' => 37.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjyEUssfNKuDIUGQbr8_BZLvpkgMhLqDFJbg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 60,
                'nombre' => 'Sándwich Suculento',
                'descripcion' => 'Sándwich de chorizo con morrón y manzana.',
                'id_categoria' => 4,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4SczXPWv_H7gGeJ-zGhGjb5INGEPY9NFNfQ&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 61,
                'nombre' => 'Sándwich De chola',
                'descripcion' => 'Pierna de cerdo con escabeche casero.',
                'id_categoria' => 4,
                'precio' => 34.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://cdn.bolivia.com/gastronomia/2018/03/12/sandwich-de-chola-boliviano-3575.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 62,
                'nombre' => 'Vegetariano clásico',
                'descripcion' => 'Pan integral con vegetales y queso.',
                'id_categoria' => 4,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.hola.com/horizon/landscape/294c1b2a256b-sandwich-adobe-t.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 63,
                'nombre' => 'Sándwich De cordero',
                'descripcion' => 'Cordero con cebolla y huacataya.',
                'id_categoria' => 4,
                'precio' => 39.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKQmtL4xlsBL_3GPgLHqOCz7MAyxMWlgjV7Q&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 64,
                'nombre' => 'Clásico',
                'descripcion' => 'Jamón artesanal con queso.',
                'id_categoria' => 4,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1ko3POLS4fFIHPdDAlp3VlEJBaZRJkqYBfw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 65,
                'nombre' => 'Croissant gratinado',
                'descripcion' => 'Croissant con jamón y queso.',
                'id_categoria' => 4,
                'precio' => 23.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://okdiario.com/img/2022/04/13/croissant-jamon-queso.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 66,
                'nombre' => 'De carne marinada',
                'descripcion' => 'Carne marinada con verduras.',
                'id_categoria' => 4,
                'precio' => 39.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk0veXppSuXXWyS5AO0I9v2RWrsA3m-qX2Og&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 67,
                'nombre' => 'Empanada Capresse',
                'descripcion' => 'Dos empanadas fritas con queso Dambo, tomate y albahaca.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://static.wixstatic.com/media/e4fb8f_62c5f36c5fff4201b0e76661d4821f98~mv2.jpg/v1/fill/w_547,h_540,al_c,lg_1,q_80,enc_avif,quality_auto/e4fb8f_62c5f36c5fff4201b0e76661d4821f98~mv2.jpg',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 68,
                'nombre' => 'Empanada Queso',
                'descripcion' => 'Dos empanadas fritas con queso suave.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO3Hpr0f-YzpFMJLNFmbR5eh-7YeH5Aj_pYA&s',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 69,
                'nombre' => 'Empanada Pollo',
                'descripcion' => 'Dos empanadas fritas con relleno de pollo criollo.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqhO4chgsxpHSEvlt78sxq3SAVvap8MpwC-g&s',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 70,
                'nombre' => 'Empanada Espinaca y Queso',
                'descripcion' => 'Dos empanadas fritas con espinaca y queso ricotta.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.goya.com/wp-content/uploads/2023/10/spinachempanadas.jpg',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 71,
                'nombre' => 'Empanada Dulce de leche y queso',
                'descripcion' => 'Dos empanadas fritas rellenas de dulce de leche y queso.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvo1ZSMCqrjJsz3WP4Fxb7ub4Yd1fev7-THA&s',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 72,
                'nombre' => 'Empanada Carne y queso provolone',
                'descripcion' => 'Dos empanadas fritas con carne condimentada y queso provolone.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX1lEAAIJFkLEWlFnOAuxPhfP3XXOfJUEcgA&s',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 73,
                'nombre' => 'Combo 6 empanadas',
                'descripcion' => '2 capresse, 2 pollo y 2 queso.',
                'id_categoria' => 5,
                'precio' => 48.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFHFPiFdbVgl8EvUwMfIZmmEZUyUruLsiNB2-5UWAJ70Msu0E8r1Dx4hR5GEQRWezy9dM&usqp=CAU',
                'eliminado' => 1,
            ],
            [
                'id_producto' => 100,
                'nombre' => 'Aeropress',
                'descripcion' => 'Café filtrado por presión con Aeropress.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://i5.walmartimages.com/seo/AeroPress-Coffee-and-Espresso-Maker-Black_a068b37a-449b-42b4-9723-02a4987e33ef.9befcbc3a932718cde45b2cf4d0bf6b9.jpeg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 101,
                'nombre' => 'Prensa Francesa',
                'descripcion' => 'Método clásico por inmersión.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://i5.walmartimages.com/asr/ad343d45-a624-4850-8671-19ca90b4a4d6.0cee947e573f8b2cec337deaca244664.jpeg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 102,
                'nombre' => 'Chemex',
                'descripcion' => 'Filtrado lento para sabores limpios.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwl0se28a21jwQv4tckgUkBgOhknG-swunmA&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 103,
                'nombre' => 'V60',
                'descripcion' => 'Método de vertido controlado.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUsp1hAIZvPmjb8twR-Tsy3XB-UMSH_s-WSg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 104,
                'nombre' => 'Siphon',
                'descripcion' => 'Café preparado con vacío y vapor.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://m.media-amazon.com/images/I/61XtvwhkmvL._AC_UF894,1000_QL80_.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 105,
                'nombre' => 'Mocca Master',
                'descripcion' => 'Destilado automático de café.',
                'id_categoria' => 6,
                'precio' => 17.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://assets.manufactum.de/assets/img/0011/00116755/0011675511-01.jpg/moccamaster-kbgt-thermos-jug.jpg?profile=pdsmain_1500',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 106,
                'nombre' => 'Shakerato',
                'descripcion' => 'Espresso con naranja y almíbar.',
                'id_categoria' => 7,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://imag.bonviveur.com/shakerato-casero.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 107,
                'nombre' => 'Espresso Tonic',
                'descripcion' => 'Espresso mezclado con agua tónica.',
                'id_categoria' => 7,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://kitchenaid.com.au/cdn/shop/articles/Espresso_Tonic.png?v=1724736180',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 108,
                'nombre' => 'Café frappeado',
                'descripcion' => 'Café batido frío.',
                'id_categoria' => 7,
                'precio' => 27.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://imag.bonviveur.com/degustando-cafe-frappe.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 109,
                'nombre' => 'Strawberry Matcha Latte',
                'descripcion' => 'Matcha verde con fresa.',
                'id_categoria' => 8,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.siftandsimmer.com/wp-content/uploads/2024/06/IMG_3139-featured.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 110,
                'nombre' => 'Ice Tea',
                'descripcion' => 'Infusión fría de té.',
                'id_categoria' => 8,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://bakingamoment.com/wp-content/uploads/2024/05/IMG_3367-iced-tea.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 111,
                'nombre' => 'Sultana',
                'descripcion' => 'Infusión de flor de café deshidratada.',
                'id_categoria' => 8,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu3933OEN-UKjpTrgz2Td8eJbSe1Uwcy9Dkg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 112,
                'nombre' => 'Power Zumo',
                'descripcion' => 'Leche texturizada con superalimentos.',
                'id_categoria' => 8,
                'precio' => 24.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t1.6435-9/149459866_1837864759715244_3424321802166537771_n.jpg?stp=dst-jpg_p526x296_tt6&_nc_cat=102&ccb=1-7&_nc_sid=127cfc&_nc_ohc=vOXvR_p_HgkQ7kNvwEDwruD&_nc_oc=AdkleBt1DFR4XQTRDg9an66Oal7XlxTtTeYw0zdyaILZ_FJy2Kcfp7pNgCoSJ5m9ChTPlpb-vZoYlHQscyq12mUo&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=FkFCl67ohixG_PKoAaEVLA&oh=00_AfPfkxC-7Se9gjNHP2EoNkwBf5S1oZVv4cMgI2_zUhwOGg&oe=686B00AE',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 113,
                'nombre' => 'Desayuno Typica',
                'descripcion' => 'Yuca rostie, tocino, huevo y k’allu.',
                'id_categoria' => 9,
                'precio' => 49.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6WtI6Y4QIsRlM9ZzeAj1UNYKNGEAGNn6Tdg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 114,
                'nombre' => 'Desayuno Saludable',
                'descripcion' => 'Avena, chía, frutas y leche.',
                'id_categoria' => 9,
                'precio' => 32.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpEKX1vd-qX41aEUe5NIh_fk_IYrxVMGyJAg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 115,
                'nombre' => 'Desayuno Waso',
                'descripcion' => 'Carne salteada con huevo y pan.',
                'id_categoria' => 9,
                'precio' => 50.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ8kDouM0uJgSCLgHAQpS7pJKRjhBDB1gjoA&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 116,
                'nombre' => 'Desayuno Compartido',
                'descripcion' => 'Ideal para dos personas.',
                'id_categoria' => 9,
                'precio' => 92.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPAHWELXJpVuugI0z4iUtB1UrwlVeWZo_Myw&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 117,
                'nombre' => 'Panqueques',
                'descripcion' => 'Panqueques con miel y mantequilla.',
                'id_categoria' => 9,
                'precio' => 23.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUHkrl4W6jGXTNHOxAj8jDVmi4xTLFpdVrOg&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 118,
                'nombre' => 'Bowl Açaí',
                'descripcion' => 'Açaí con frutas y granola.',
                'id_categoria' => 9,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://media.istockphoto.com/id/678197488/photo/acai-bowl.jpg?s=612x612&w=0&k=20&c=dNlyzfWj2qwyh0TX9FWm6gnhMdHx_Yci0AxCJovLOP0=',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 119,
                'nombre' => 'Sándwich de Pollo',
                'descripcion' => 'Pollo con rúcula y cebolla.',
                'id_categoria' => 10,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t39.30808-6/470048297_2921804821321227_7081634567063527626_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=127cfc&_nc_ohc=eLswaHD2x9YQ7kNvwHRtIvY&_nc_oc=AdmW2O3UKH6YDrs3vXM3oW3ksi0jgQGUkHrsjp0iBOu_eFT7xrJXZld0gYjahg5M_QxF1IJPS_eXnzhku_b7cLxb&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=wX63nWxDQa3A-2RMOIZvMw&oh=00_AfPpLrEZktS6vj1owXlJpKxrHP9dFc7Jkvf2grFFZq9BcQ&oe=684942E0',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 120,
                'nombre' => 'Sándwich de Charque',
                'descripcion' => 'Charque de res con salsa.',
                'id_categoria' => 10,
                'precio' => 36.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-2.fna.fbcdn.net/v/t1.6435-9/65804427_1315509651950760_5044362776173084672_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=InXJ0ASAzBsQ7kNvwE4XVbl&_nc_oc=AdnImwyC17-7kHihUzzVKl8POXFmPO4ayLZkqetRlkfd6esGx1Gv041mozCPXXdX2pYSsP4ZN6PYPBlc8dFpB-dr&_nc_zt=23&_nc_ht=scontent.flpb1-2.fna&_nc_gid=-Gw1xZ-ByPxlMW_DIpFNFA&oh=00_AfOo45NQpjyNIBbS1VN2aCPYMSqiaWEUsir_qCwD00miJQ&oe=686B018A',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 121,
                'nombre' => 'Sándwich de Palta',
                'descripcion' => 'Palta, cebollín y tomate.',
                'id_categoria' => 10,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t1.6435-9/124199709_1761416514026736_990185108809046140_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=3a1ebe&_nc_ohc=_z4zBKglgb4Q7kNvwEM4sYC&_nc_oc=AdnAah7oEPKv7-8N-lSjqjKpb_abUny8VSHJ-ZaHERn2fAQd_dVf6rvp6BUpwO5wB_MopLsP_xkPMH4S_-hL6df1&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=X3ryN4VQkVxwk8sOLPaydQ&oh=00_AfMbbvy1sL81FkYyHNQUU51gAiOOqbLIlSUj5uUtIzYPyw&oe=686AF930',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 122,
                'nombre' => 'Ensalada de Quinua',
                'descripcion' => 'Mix de quinua y verduras.',
                'id_categoria' => 11,
                'precio' => 28.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://cdn.bolivia.com/gastronomia/2014/07/29/ensalada-de-quinua-con-finas-hierbas-3282.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 123,
                'nombre' => 'Ensalada de Manzana y Jamón',
                'descripcion' => 'Lechugas con jamón y manzana.',
                'id_categoria' => 11,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-2.fna.fbcdn.net/v/t39.30808-6/482116594_2997312130437162_7052459527258144532_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=127cfc&_nc_ohc=NXuUVwQZpNsQ7kNvwEamyQz&_nc_oc=AdmlwXXCSb7w9F5NvgvBlEYr0NQsy852PQyxG_YWOcKu3mNo5bffWPEOjWkkZ054T4ySee8Dzq6NNVvuT5TTzGrX&_nc_zt=23&_nc_ht=scontent.flpb1-2.fna&_nc_gid=GXNcN6he2wlGsG6_R0oIKA&oh=00_AfOeVx4FPBmzGX1UXOm_uFM9seaILN7yNBWnWy_P6cH8aw&oe=6849701B',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 124,
                'nombre' => 'Empanada Capresse',
                'descripcion' => 'Queso, tomate y albahaca.',
                'id_categoria' => 12,
                'precio' => 19.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.laylita.com/recetas/wp-content/uploads/Empanadas-caprese.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 125,
                'nombre' => 'Empanada de Queso',
                'descripcion' => 'Rellena de queso.',
                'id_categoria' => 12,
                'precio' => 19.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://fenixempre.com/wp-content/uploads/2024/09/empanadas-de-queso.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 126,
                'nombre' => 'Empanada de Pollo',
                'descripcion' => 'Pollo, cebolla y picante.',
                'id_categoria' => 12,
                'precio' => 19.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://fridolin.com.bo/wp-content/uploads/2021/03/empanada-de-pollo-mediana-3.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 127,
                'nombre' => 'Empanada Espinaca y Queso',
                'descripcion' => 'Espinaca con queso.',
                'id_categoria' => 12,
                'precio' => 19.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf46l-636a73MYhEO9WVW_qqRVxdCCTmLM4Q&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 128,
                'nombre' => 'Empanada Dulce de leche y queso',
                'descripcion' => 'Dulce de leche y queso.',
                'id_categoria' => 12,
                'precio' => 19.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t39.30808-6/463201690_2865195576982152_1571649315700600970_n.png?_nc_cat=106&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=T8kukAAF-_8Q7kNvwFL9bYq&_nc_oc=AdlretF38a2Tt26GIQPDUD6oGnyyUe6SwvHZgMcZn2ipa0GHM5l1RZWS8fCELFWv-h60Yt0H8dsJfz7GEmTyWsFu&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=lpOUSmsMACfCinR_kvrIvw&oh=00_AfMXz1eknbpARLU9vG5p5ItcQTb1_fGAgfP4MWeh4A6-pQ&oe=68495726',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 129,
                'nombre' => 'Combo 6 Empanadas',
                'descripcion' => 'Combinación de sabores.',
                'id_categoria' => 12,
                'precio' => 42.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t39.30808-6/462780177_2861003734068003_4508086601668429192_n.png?_nc_cat=101&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=_gKSJtjYE8EQ7kNvwGiHkrU&_nc_oc=Adm10P0szuZO1KWHx5sPaWFmZbr8lZE6VrPy89g5M7WoinE4ztmGlN18xFkQNDqupSkbIZCoNB4iGTQWG0tHT7Xu&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=hBogcntqaz8XnwY3QS1ZdA&oh=00_AfMp1keLJHr5vWV4QtXSPn4EDcSECn7mJrYRmJ6sONedSA&oe=684966D1',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 130,
                'nombre' => 'Chorizo',
                'descripcion' => 'Chorizos al vino blanco.',
                'id_categoria' => 13,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.shutterstock.com/image-photo/tapa-de-chorizo-typical-spanish-600nw-2463638423.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 131,
                'nombre' => 'Cuñapés Fritos',
                'descripcion' => 'Cuñapés crocantes.',
                'id_categoria' => 13,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.paulinacocina.net/wp-content/uploads/2024/05/receta-de-cunape-Paulina-Cocina-Recetas-1722430369.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 132,
                'nombre' => 'Anticucho',
                'descripcion' => 'Corazón de res a la plancha.',
                'id_categoria' => 13,
                'precio' => 28.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-2.fna.fbcdn.net/v/t39.30808-6/480576285_2981667402001635_3765985445225545452_n.jpg?stp=dst-jpg_s640x640_tt6&_nc_cat=103&ccb=1-7&_nc_sid=3a1ebe&_nc_ohc=iwyIrRKT0mkQ7kNvwGzQ0Gi&_nc_oc=AdkzyC1yQ5QGeFwgpFBXEeFZnVJ6jQJpG_okodq_Lfvtjhn3C3YpEOKa1EEsDXQr_w_nqzA_G_gtPWK8ngAfzk2R&_nc_zt=23&_nc_ht=scontent.flpb1-2.fna&_nc_gid=_gwqGT4E5QpSFtjlXScjZQ&oh=00_AfMsFH1m02GsN1XvM7n0AcbvWq26RDJNWI7ZL9njiDDlLg&oe=68495A59',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 133,
                'nombre' => 'Singani Mule',
                'descripcion' => 'Singani con almíbar de jengibre.',
                'id_categoria' => 14,
                'precio' => 32.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t1.6435-9/118868529_2063638057268530_5637600697489315471_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=3a1ebe&_nc_ohc=jgh58R3quuwQ7kNvwGGC_Wq&_nc_oc=AdmoyDYdxhL3nCVTNkp5Av1xx2O2MHHeWQe4iQMxb4Zx0vhfgpsrMh11RFoEO9BpkkDBFM8LNlhDB91MCOja7Vcx&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=vfbns6Z27DBRQAUAe6ADuQ&oh=00_AfOT91Q56m1XALP4aPMhCsycOdPsgR-vGspzGcObL4GWsw&oe=686B108F',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 134,
                'nombre' => 'Sultana con Sultana',
                'descripcion' => 'Infusión de sultana y singani.',
                'id_categoria' => 14,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-2.fna.fbcdn.net/v/t39.30808-6/473067386_2944887129012996_7629615466183970538_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=833d8c&_nc_ohc=0jwXuInNHaIQ7kNvwE3L7jL&_nc_oc=AdmuPZjA7EQgT7WF0vrawko_egAheuwST2pCKYcsMYolJhsWRl45CK8Z-1h2SUYvYphsAKOeW3Vh23C1YldlXbjy&_nc_zt=23&_nc_ht=scontent.flpb1-2.fna&_nc_gid=VD0Spp4UD92JM-l78vxoEQ&oh=00_AfOeQLBkdQxGa5-DKHjhDm0pXikvBLQFnfDQcgGl3bz2Kw&oe=68496DEC',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 135,
                'nombre' => 'Espresso Martini',
                'descripcion' => 'Espresso, vodka y naranja.',
                'id_categoria' => 14,
                'precio' => 40.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://scontent.flpb1-1.fna.fbcdn.net/v/t39.30808-6/480732638_1036995795122756_5442305628272690636_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=127cfc&_nc_ohc=fU2GCozOAs0Q7kNvwFgoQXV&_nc_oc=Adk7z015KodcVAGRum9CNfWIf8_8HsJGDTHKj8N6snw8lU47jwQT8jqQ_WoyhftbgLgzboPAQZ3eLM8fWkZ1yvLu&_nc_zt=23&_nc_ht=scontent.flpb1-1.fna&_nc_gid=4ndrmYrYEHuc13bK48_NoA&oh=00_AfOXrtGs2z4lHKWg7-s2-KLaOlKo_u6M0btLUekwQvtpzw&oe=684963C0',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 136,
                'nombre' => 'Bendita 330ml',
                'descripcion' => 'Cerveza artesanal.',
                'id_categoria' => 15,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7z1ceRdJ6F5V62jsHuDp8CmBPU0z8EsDE7A&s',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 137,
                'nombre' => 'Prost 550ml',
                'descripcion' => 'Cerveza grande Prost.',
                'id_categoria' => 15,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.megalicor.bo/wp-content/uploads/2020/05/10290089.jpg',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 138,
                'nombre' => 'Riesling Copa',
                'descripcion' => 'Campos de Solana.',
                'id_categoria' => 16,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.diprimsa.es/wp-content/uploads/2015/02/BEYER-RIESLING-75.png',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 139,
                'nombre' => 'Cabernet Sauvignon Copa',
                'descripcion' => 'Campos de Solana.',
                'id_categoria' => 16,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://winestore.com.bo/wp-content/uploads/2023/02/7804320116846.webp',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 140,
                'nombre' => 'Moscato Copa',
                'descripcion' => 'Bodega Tierra Roja.',
                'id_categoria' => 16,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://winestore.com.bo/wp-content/uploads/2022/12/7772115570176.webp',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 141,
                'nombre' => 'Orange Copa',
                'descripcion' => 'Bodega Cañon Escondido.',
                'id_categoria' => 16,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://winestore.com.bo/wp-content/uploads/2023/01/7772115830089.webp',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 142,
                'nombre' => 'Tannat Copa',
                'descripcion' => 'Bodega Cañon Escondido.',
                'id_categoria' => 16,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://winestore.com.bo/wp-content/uploads/2023/01/7772115830065.webp',
                'eliminado' => 0,
            ],
            [
                'id_producto' => 143,
                'nombre' => 'Empanada Carne y queso provolone',
                'descripcion' => 'Dos empanadas fritas con carne condimentada y queso provolone.',
                'id_categoria' => 12,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 20,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX1lEAAIJFkLEWlFnOAuxPhfP3XXOfJUEcgA&s',
                'eliminado' => 0,
            ],
        ]);
    }
}
