<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('producto')->insert([
            [
                'nombre' => 'Café Americano',
                'descripcion' => 'Café negro caliente',
                'id_categoria' => 1,
                'precio' => 8.50,
                'disponibilidad' => 0,
                'cantidad_disponible' => 2,
                'imagen' => 'https://us.123rf.com/450wm/farknot/farknot1801/farknot180100055/94523530-imagen-del-primer-de-la-taza-de-café-caliente-de-americano-en-la-tabla-de-madera-del-vintage-en.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Latte',
                'descripcion' => 'Café con leche vaporizada',
                'id_categoria' => 1,
                'precio' => 10.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 5,
                'imagen' => 'https://izlah.mx/cdn/shop/products/Bxtr_Vintage_2.png?v=1589587917',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Té verde',
                'descripcion' => 'Infusión de té verde',
                'id_categoria' => 1,
                'precio' => 9.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 1,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVli4Sh8y9-OskZmWtaiKjOhS4ocpuApZvFg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Jugo de naranja',
                'descripcion' => 'Jugo natural exprimido',
                'id_categoria' => 2,
                'precio' => 9.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://us.123rf.com/450wm/nadezhda1906/nadezhda19061705/nadezhda1906170500137/77961693-escena-de-la-mañana-de-jugos-de-naranja-fresca-servido-en-el-bar.jpg?ver=6',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Cheesecake',
                'descripcion' => 'Torta de queso crema',
                'id_categoria' => 3,
                'precio' => 12.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://images.ctfassets.net/trvmqu12jq2l/VkBle3ndRRRtHWrOhaKKj/01190beab12083d50f421e7efdc3b404/CxBlog-DD-CheesecakeFactory-SaltedCaramel.jpg?q=70&w=480',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Pastel de frutillas',
                'descripcion' => 'pastel con frutillas y queso',
                'id_categoria' => 3,
                'precio' => 18.00,
                'disponibilidad' => 0,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU6MQw_fCwfVFSeAQAysA-KceDKAVWYQXSmw&s',
                'eliminado' => 1,
            ],
            [
                'nombre' => 'Macchiato',
                'descripcion' => 'Espresso manchado con una gota de leche texturizada.',
                'id_categoria' => 1,
                'precio' => 15.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://www.acouplecooks.com/wp-content/uploads/2020/10/how-to-make-a-macchiato-003s.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Espresso Americano',
                'descripcion' => 'Doble shot de espresso diluido en agua.',
                'id_categoria' => 1,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://gourmetdemexico.com.mx/wp-content/uploads/2016/08/field_image_head-espresso.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Cortado',
                'descripcion' => 'Leche texturizada con la temperatura ideal para cortar el espresso.',
                'id_categoria' => 1,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsD2RKaN-OY-35n37KdqGfpg4CgCgIGvH8VA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Flat White',
                'descripcion' => 'Doble ristretto con leche texturizada.',
                'id_categoria' => 1,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/flat-white-d8ada0f.jpg?quality=90&resize=440,400',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Submarino',
                'descripcion' => 'Leche texturizada con una barra de chocolate amargo entero.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 2,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiDoyB26ej8-yH7LmF2I7uOMm81SgT1R5sqg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Té Latte',
                'descripcion' => 'Té con leche.',
                'id_categoria' => 1,
                'precio' => 22.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://i.blogs.es/e97540/te-chai-latte/1366_2000.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Chocolate caliente',
                'descripcion' => 'Cocoa con leche, acompañada de dos marshmallows.',
                'id_categoria' => 1,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE4-CtCbPsEWMl3jGuPwXkSaNc0TadMMYiTw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Té Chai',
                'descripcion' => 'Té negro, especias y leche texturizada.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 3,
                'imagen' => 'https://www.splenda.com/wp-content/themes/bistrotheme/assets/recipe-images/chai-tea-blend.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Matcha Latte',
                'descripcion' => 'Té verde matcha con leche texturizada.',
                'id_categoria' => 1,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 4,
                'imagen' => 'https://munchingwithmariyah.com/wp-content/uploads/2020/06/IMG_0748.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Niebla en Londres',
                'descripcion' => 'Té negro, especias y leche texturizada.',
                'id_categoria' => 1,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRLd71Ip3S8DnXAInWaFxw1TGtvNgJDLLhJIZq29PuijnO9z15YE2B0FKJgRjlw5boO_A&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Coldbrew',
                'descripcion' => 'Café frío de origen: extraído durante 16 horas.',
                'id_categoria' => 2,
                'precio' => 22.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpiFaDmfujrauZMwSXoWbTJTSbbFd94xlfQw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Café con hielo',
                'descripcion' => 'Café de origen destilado con hielos.',
                'id_categoria' => 2,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5tS0no6EB1MOMI9ug6Bn9BC0_sJry71iLdQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Latte frío',
                'descripcion' => 'Doble shot de espresso, leche texturizada y hielo.',
                'id_categoria' => 2,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN_f3AtqsjG9nkkbUvnug0mSZOtKkgmH9Rog&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Café con leche frappeado',
                'descripcion' => 'Todo ya está dicho.',
                'id_categoria' => 2,
                'precio' => 28.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFYEuJgeYsnql0MFK6btdouwtM2AZP7DZqgXPgYWwmjarpeyXkK2wWhW6w2spGkDzvxEY&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Affogato',
                'descripcion' => 'Dos porciones de helado de vainilla con doble shot de espresso.',
                'id_categoria' => 2,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://static01.nyt.com/images/2021/08/15/magazine/affogato/affogato-mediumSquareAt3X-v2.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Shakerato',
                'descripcion' => 'Bebida refrescante a base de espresso, naranja y albahaca.',
                'id_categoria' => 2,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQno3nzqXK0a36Wcqfq2oCXW-LXJNHA5Qrnpw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Espresso Tonic',
                'descripcion' => 'Dos shots de espresso y agua tónica.',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://res.cloudinary.com/htt8g4cd/images/f_auto,q_auto/v1730823639/wp/07_23_Espresso_Tonic_HERO_Stocksy_4062559_1920x1280/07_23_Espresso_Tonic_HERO_Stocksy_4062559_1920x1280.jpg?_i=AA',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Jugos naturales',
                'descripcion' => 'Jugos naturales (con leche).',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSjMBTsZ_ExFsCLjygT2G0OYpFPm1JMXm2lg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Mix de frutas',
                'descripcion' => 'Mix de frutas.',
                'id_categoria' => 2,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBekkfntZCXh7BkAfNSAxshjrqbNDosbqjMQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Limonada',
                'descripcion' => 'Limonada (puedes pedirla con hierba buena).',
                'id_categoria' => 2,
                'precio' => 10.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.conasi.eu/blog/wp-content/uploads/2019/09/limonada-de-albahaca-1.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Strawberry Matcha Latte',
                'descripcion' => 'Matcha con fresa y leche.',
                'id_categoria' => 2,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0CLS6WcPUlhX7Wc75js56dkgeDGyCCdk1lQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Ice Tea',
                'descripcion' => 'Té frío de infusiones clásicas o especiales.',
                'id_categoria' => 2,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0JqdakweKyrQByMMYMA6Cy9XiXu8MMOBBsw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Cheesecake de limón',
                'descripcion' => 'Cheesecake con base de galleta y salsa de limón.',
                'id_categoria' => 3,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFmE0hxPLjx5bEUhsNvOTcKxbD1XijhZseug&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Cheesecake de maracuyá',
                'descripcion' => 'Cheesecake con base de galleta de chocolate y salsa de maracuyá.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThtxktek3xo_UccVBO57IHLnYsIDiQJ6fJ8TVXpNpsbtPgiCJgeOUqAHlGQK9ZR06IEX4&usqp=CAU',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Torta de zanahoria',
                'descripcion' => 'Torta de zanahoria con cobertura de queso crema.',
                'id_categoria' => 3,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0JYLWJBlRtgO8Az2pDV9ffpBxuWeghz1xMQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Crepes de dulce de leche con fruta',
                'descripcion' => 'Rellenos de dulce de leche acompañados con frutas de temporada.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://d1uz88p17r663j.cloudfront.net/original/a83618e0a68ec34aa3e28ad3171f8705_Dulce_de_Leche_Crepes_with_Banana.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Brownie',
                'descripcion' => 'Hecho en casa, en su punto.',
                'id_categoria' => 3,
                'precio' => 18.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://i.blogs.es/22b5c5/brownie/840_560.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Apple Crumble',
                'descripcion' => 'Tarta de manzana con yogur de vainilla.',
                'id_categoria' => 3,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://hips.hearstapps.com/hmg-prod/images/apple-crumble-recipe-2-66c641fec6b40.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=1200:*',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Tostadas francesas al cubo',
                'descripcion' => 'Pan de molde con relleno de pancakes.',
                'id_categoria' => 3,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy1TkSx2soZIyCOiwlf_U4xsuPUhB01EjyEQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Frappé fruta de temporada',
                'descripcion' => 'Frappé de fruta de temporada.',
                'id_categoria' => 3,
                'precio' => 24.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://servinox.com.mx/blog/wp-content/uploads/2015/05/smoothie-and-coffee-244x300.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Frappé pie de limón',
                'descripcion' => 'Frappé con sabor a pie de limón.',
                'id_categoria' => 3,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSbskqbvpF33oWSFOHp28jkgGZ_2_Az3LV3w&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Frappé orejón',
                'descripcion' => 'Frappé orejón.',
                'id_categoria' => 3,
                'precio' => 26.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgUJUaar8wXmdm6uwOiJwqLkr9hamaVrBQOw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Desayuno Typica',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 49.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcMCFsVazxz-KY-Z9DjycqzaTx2VNflk-d3w&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Desayuno Americano',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 46.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRY2U8ANg31mvvw4345_maWqeWgrMBiMkCfQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Desayuno Saludable',
                'descripcion' => 'Incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 34.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQN5FjmfC6-V_q9ProMil7LTUtVncaiBbuNg&',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Duo de Croissants',
                'descripcion' => 'Se elige uno dulce y uno salado.',
                'id_categoria' => 4,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuj1nH0t96XWJ_Zs-S1IEW1FG0GysQUfTcDA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Panqueques',
                'descripcion' => 'Dos panqueques esponjosos de mantequilla.',
                'id_categoria' => 4,
                'precio' => 25.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShsTFR136GmyqoEJIaTuYvPJtf2vJAmcv4AA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Croissant de chocolate',
                'descripcion' => 'Croissant de masa hojaldrada, relleno con chocolate.',
                'id_categoria' => 4,
                'precio' => 16.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://comedera.com/wp-content/uploads/sites/9/2022/02/croissant-relleno-de-chocolate.jpg?w=4096',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Ensalada de frutas',
                'descripcion' => 'Variedad de frutas de estación con jugo de naranja.',
                'id_categoria' => 4,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIIwMBo0ttWTw2CSYteKz9WsLlJXTRDYRyLw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Bowl Açaí',
                'descripcion' => 'Deliciosa mezcla de açaí y frutas de estación.',
                'id_categoria' => 4,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV7mufGZULOKQzdLDu0XupPxiR4HKusmEULQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Desayuno Waso',
                'descripcion' => 'Carne salteada a lo Waso y verduras con arroz.',
                'id_categoria' => 4,
                'precio' => 35.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://d36fw6y2wq3bat.cloudfront.net/recipes/salteado-de-arroz-verduras-y-ternera/900/salteado-de-arroz-verduras-y-ternera_version_1652877970.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Desayuno Compartido',
                'descripcion' => 'Para compartir, incluye jugo y café.',
                'id_categoria' => 4,
                'precio' => 95.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNCvgJi1x_tY6wLCJ-ZeN7QQOXcPQCsvD3XQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Chorizo',
                'descripcion' => 'Dos chorizos al vino blanco con papas y chucrut.',
                'id_categoria' => 4,
                'precio' => 38.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXhmu2Rm7AV1hWFCDTrD_p54Otr73h7c5QHw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Cuñapés fritos',
                'descripcion' => 'Cuñapés fritos acompañados con salsa de sésamo.',
                'id_categoria' => 4,
                'precio' => 20.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg6Fm34MUp8eXQt7bvKiWL5UVU2U3C1xapfg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Anticucho',
                'descripcion' => 'Corazón de res con papas y ají.',
                'id_categoria' => 4,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMJSpbzj9rEbLzZXV6lxYpz4wFYJxIMUy8gQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Combo rellenos',
                'descripcion' => 'Plátano dulce con carne deshilachada y queso.',
                'id_categoria' => 4,
                'precio' => 41.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLScw7YyR4a5JZnkD3ko4HeqV8DyaGrpQm9g&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Charque',
                'descripcion' => 'Charque con salsa de tres quesos en pan marraqueta.',
                'id_categoria' => 4,
                'precio' => 38.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-b_kViJ4JWVG9jbnE2JwVk5iuwmcjJXhXvw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Sándwich palta',
                'descripcion' => 'Sándwich de palta con cebolín y tomate confitado.',
                'id_categoria' => 4,
                'precio' => 27.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRigIPg5uKzAvxekEAFMd3jPVfzmC-yWGM0Lg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Sándwich Pollo',
                'descripcion' => 'Sándwich de pollo con cebolla dulce.',
                'id_categoria' => 4,
                'precio' => 37.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjyEUssfNKuDIUGQbr8_BZLvpkgMhLqDFJbg&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Sándwich Suculento',
                'descripcion' => 'Sándwich de chorizo con morrón y manzana.',
                'id_categoria' => 4,
                'precio' => 30.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4SczXPWv_H7gGeJ-zGhGjb5INGEPY9NFNfQ&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Sándwich De chola',
                'descripcion' => 'Pierna de cerdo con escabeche casero.',
                'id_categoria' => 4,
                'precio' => 34.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://cdn.bolivia.com/gastronomia/2018/03/12/sandwich-de-chola-boliviano-3575.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Vegetariano clásico',
                'descripcion' => 'Pan integral con vegetales y queso.',
                'id_categoria' => 4,
                'precio' => 31.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.hola.com/horizon/landscape/294c1b2a256b-sandwich-adobe-t.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Sándwich De cordero',
                'descripcion' => 'Cordero con cebolla y huacataya.',
                'id_categoria' => 4,
                'precio' => 39.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKQmtL4xlsBL_3GPgLHqOCz7MAyxMWlgjV7Q&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Clásico',
                'descripcion' => 'Jamón artesanal con queso.',
                'id_categoria' => 4,
                'precio' => 29.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1ko3POLS4fFIHPdDAlp3VlEJBaZRJkqYBfw&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Croissant gratinado',
                'descripcion' => 'Croissant con jamón y queso.',
                'id_categoria' => 4,
                'precio' => 23.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://okdiario.com/img/2022/04/13/croissant-jamon-queso.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'De carne marinada',
                'descripcion' => 'Carne marinada con verduras.',
                'id_categoria' => 4,
                'precio' => 39.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk0veXppSuXXWyS5AO0I9v2RWrsA3m-qX2Og&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Capresse',
                'descripcion' => 'Dos empanadas fritas con queso Dambo, tomate y albahaca.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://static.wixstatic.com/media/e4fb8f_62c5f36c5fff4201b0e76661d4821f98~mv2.jpg/v1/fill/w_547,h_540,al_c,lg_1,q_80,enc_avif,quality_auto/e4fb8f_62c5f36c5fff4201b0e76661d4821f98~mv2.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Queso',
                'descripcion' => 'Dos empanadas fritas con queso suave.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO3Hpr0f-YzpFMJLNFmbR5eh-7YeH5Aj_pYA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Pollo',
                'descripcion' => 'Dos empanadas fritas con relleno de pollo criollo.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqhO4chgsxpHSEvlt78sxq3SAVvap8MpwC-g&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Espinaca y Queso',
                'descripcion' => 'Dos empanadas fritas con espinaca y queso ricotta.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://www.goya.com/wp-content/uploads/2023/10/spinachempanadas.jpg',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Dulce de leche y queso',
                'descripcion' => 'Dos empanadas fritas rellenas de dulce de leche y queso.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvo1ZSMCqrjJsz3WP4Fxb7ub4Yd1fev7-THA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Empanada Carne y queso provolone',
                'descripcion' => 'Dos empanadas fritas con carne condimentada y queso provolone.',
                'id_categoria' => 5,
                'precio' => 21.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX1lEAAIJFkLEWlFnOAuxPhfP3XXOfJUEcgA&s',
                'eliminado' => 0,
            ],
            [
                'nombre' => 'Combo 6 empanadas',
                'descripcion' => '2 capresse, 2 pollo y 2 queso.',
                'id_categoria' => 5,
                'precio' => 48.00,
                'disponibilidad' => 1,
                'cantidad_disponible' => 0,
                'imagen' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFHFPiFdbVgl8EvUwMfIZmmEZUyUruLsiNB2-5UWAJ70Msu0E8r1Dx4hR5GEQRWezy9dM&usqp=CAU',
                'eliminado' => 0,
            ],
            

        ]);
    }
}
